apiVersion: v1
kind: ConfigMap
metadata: 
  name: glpi-config
  namespace: glpi 
data: 
  GLPI_LANG: "en_US"
  VERSION: "10.0.7"
  GLPI_MARKETPLACE_DIR: /var/www/html/marketplace
  GLPI_VAR_DIR: /var/lib/glpi
  GLPI_DOC_DIR: /var/lib/glpi
  GLPI_CRON_DIR: /var/lib/glpi/_cron
  GLPI_DUMP_DIR: /var/lib/glpi/_dumps
  GLPI_GRAPH_DIR: /var/lib/glpi/_graphs
  GLPI_LOCK_DIR: /var/lib/glpi/_lock
  GLPI_LOG_DIR: /var/lib/glpi/_log
  GLPI_PICTURE_DIR: /var/lib/glpi/_pictures
  GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/_plugins
  GLPI_RSS_DIR:  /var/lib/glpi/_rss
  GLPI_SESSION_DIR: /var/lib/glpi/_sessions
  GLPI_TMP_DIR: /var/lib/glpi/_tmp
  GLPI_UPLOAD_DIR: /var/lib/glpi/_uploads
  GLPI_CACHE_DIR: /var/lib/glpi/_cache
  GLPI_CONFIG_DIR: /etc/glpi/config

  MARIADB_HOST: "mariadb-headless.glpi.svc.cluster.local"
  MARIADB_PORT: "3306"


--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    name: nginx-conf
  namespace: glpi 
data:
  default.conf: |-
    server {
        listen 0.0.0.0:80;
        root /var/www/html;
        location / {
            index index.php index.html;
        }
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php-fpm.glpi.svc.cluster.local:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
        }
    }