---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-files
  namespace: glpi
spec:
  # storageClassName: longhorn
  accessModes:
    # - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-marketplace
  namespace: glpi
spec:
  # storageClassName: longhorn
  accessModes:
#    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-etc
  namespace: glpi
spec:
  # storageClassName: longhorn
  accessModes:
#    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi


