apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-timezone
  namespace: glpi
spec:
  template:
    spec:
      containers:
      - image: mariadb:10.6
        imagePullPolicy: IfNotPresent
        name: base
        command:
        - sh
        - -c 
        - "mysql --host=${MARIADB_HOST} -u root -p${MARIADB_ROOT_PASSWORD} -e \"GRANT SELECT ON mysql.time_zone_name TO 'glpi'@'%'; FLUSH PRIVILEGES;\""
        envFrom: 
        - secretRef: 
            name: mariadb-glpi-secret
        - configMapRef: 
            name: mariadb-glpi-config

      restartPolicy: Never
  backoffLimit: 5
status: {}

