--- 
apiVersion: v1
kind: Secret
type: Opaque
metadata: 
  name: mariadb-glpi-secret
  namespace: glpi 
data: 
  MYSQL_RANDOM_ROOT_PASSWORD: eWVz
  MYSQL_DATABASE: Z2xwaQ==
  MYSQL_USER: Z2xwaQ==
  MYSQL_PASSWORD: Z2xwaQ==
