apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-timezone
  namespace: glpi
spec:
  template:
    spec:
      containers:
      - image: mariadb:11.4
        imagePullPolicy: IfNotPresent
        name: base
        command:
        - sh
        - -c 
        - "mariadb --host=${MARIADB_HOST} -u root -p${MARIADB_ROOT_PASSWORD} -e \"GRANT SELECT ON mysql.time_zone_name TO 'glpi'@'%'; FLUSH PRIVILEGES;\""
        envFrom: 
        - secretRef: 
            name: mariadb-glpi-secret
        - configMapRef: 
            name: mariadb-glpi-config
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
status: {}

