name: Nginx

on:
  # workflow_run:
  #   workflows: ["PHP"]
  #   types:
  #     - completed
  #   branches: 
  #     - "latest"
  #     - "10.0.*"
  #schedule:
  #  - cron: '1 1 1 * *'
  push:
    branches:
      - "latest" 
  release: 
    types: 
      - published


env:
  REGISTRY: "docker.io"
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-nginx:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@aa33708b10e362ff993539393ff100fa93ed6a27

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavors: |
            latest=true
            preffix=nginx- 
          tags: |
            type=semver,pattern={{version}} 
            type=sha,format=long 

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445
        with:
          context: ./docker/nginx/
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

